name: 'ghav human: CI'
'on':
  push:
    branches:
    - ghav/dev/1618
permissions:
  contents: read
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shard:
        - 1
        - 2
        - 3
        - 4
        - 5
    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v6
    - uses: actions/setup-node@v6
      with:
        node-version-file: .nvmrc
        cache: pnpm
    - run: pnpm install --frozen-lockfile
    - run: pnpm run test --shard=${{ matrix.shard }}/5
